#!/usr/bin/env bash
# Create the Python environment with the EXACT stack the source pipeline ran on.
#
# WHY THE VERSIONS ARE PINNED AND MUST NOT BE "FIXED"
# ---------------------------------------------------
# vLLM's sampling kernels, its attention backend, and the transformers chat-template
# implementation all affect what the model emits. A different vLLM build produces
# different text for the same prompt at temperature=0. The whole point of this run is to
# compare six arms against each other and against an existing JHU run; if two arms are
# generated by different builds, the comparison is meaningless and there is no way to tell
# after the fact which rows came from which build.
#
# So: if the detected CUDA/driver cannot support the pinned wheels, this script STOPS.
# It does not fall back to another version. Ask Wytro before deviating.
#
# Usage:
#   bash scripts/00_setup_env.sh [ENV_NAME] [--skip-gen-check]
set -euo pipefail

ENV_NAME="${1:-rewrite-vllm}"
[[ "${1:-}" == --* ]] && ENV_NAME="rewrite-vllm"
SKIP_GEN=0
for a in "$@"; do [[ "$a" == "--skip-gen-check" ]] && SKIP_GEN=1; done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ---- the pinned stack, recovered from the source environment and its runtime logs ----
PY_VERSION=3.12
PIN_TORCH=2.11.0
PIN_VLLM=0.22.0
PIN_TRANSFORMERS=5.9.0
PIN_TOKENIZERS=0.22.2
PIN_HFHUB=1.17.0
PIN_NUMPY=2.3.5
PIN_PYARROW=24.0.0
PIN_SAFETENSORS=0.7.0
PIN_TRITON=3.6.0
PIN_FLASHINFER=0.6.11.post2
PIN_XGRAMMAR=0.2.1
PIN_MSGSPEC=0.21.1
# Not in the source env (it read local parquet and never touched the Hub at runtime).
# Added here ONLY for the download path and the JSONL output; neither touches generation.
PIN_DATASETS=4.4.1
PIN_HFTRANSFER=0.1.9
PIN_ZSTANDARD=0.23.0
PIN_PYYAML=6.0.2

# torch 2.11.0 ships against CUDA 13.0; the source ran torch 2.11.0+cu130 on driver
# 580.159.04. 580.65 is the minimum driver for the CUDA 13.0 runtime.
REQ_CUDA_MAJOR=13
MIN_DRIVER=580.65
TORCH_INDEX="https://download.pytorch.org/whl/cu130"

say()  { printf '\n\033[1m== %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31m*** STOP: %s\033[0m\n\n' "$*" >&2; exit 2; }

# ===========================================================================
say "1/5  Detecting GPU, driver and CUDA"
# ===========================================================================
command -v nvidia-smi >/dev/null 2>&1 || die \
"nvidia-smi not found. This pipeline needs NVIDIA GPUs.
   If the GPUs are visible only inside a container, or after loading an environment
   module, do that first,
   then re-run this script."

nvidia-smi --query-gpu=index,name,driver_version,memory.total,compute_cap \
           --format=csv,noheader | sed 's/^/   GPU /'

DRIVER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1 | tr -d ' ')
NGPU=$(nvidia-smi --list-gpus | wc -l | tr -d ' ')
CCAP=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | head -1 | tr -d ' ')
SMI_CUDA=$(nvidia-smi | sed -n 's/.*CUDA Version: *\([0-9][0-9.]*\).*/\1/p' | head -1)
# smallest card decides whether the model fits, not whichever happens to be GPU 0
VRAM_MIB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | tr -d ' ' | sort -n | head -1)
ARCHS=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | tr -d ' ' | sort -u | tr '\n' ' ')
NARCH=$(echo "$ARCHS" | wc -w)

echo
echo "   driver_version : $DRIVER"
echo "   cuda (per smi) : ${SMI_CUDA:-unknown}"
echo "   gpu count      : $NGPU"
echo "   compute cap    : $CCAP   (sm_${CCAP//./})"
echo "   all archs      : $ARCHS"
echo "   vram (smallest): ${VRAM_MIB} MiB"
echo "   pinned target  : torch ${PIN_TORCH}+cu130, vllm ${PIN_VLLM}, CUDA ${REQ_CUDA_MAJOR}.x"

# ---- hard stop on a driver that cannot run the pinned wheels ----
ver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -1)" = "$2" ]; }
if ! ver_ge "$DRIVER" "$MIN_DRIVER"; then
  die "driver $DRIVER is too old for the pinned stack (torch ${PIN_TORCH}+cu130 needs
   CUDA ${REQ_CUDA_MAJOR}.0, which requires driver >= ${MIN_DRIVER}).

   Do NOT install an older torch/vLLM to work around this. A different vLLM build changes
   generation behaviour and destroys comparability across the six arms -- and there is no
   way to tell afterwards which rows came from which build.

   Your options, in order of preference:
     1. Update the NVIDIA driver to >= ${MIN_DRIVER}  (ask your admin).
     2. Ask Wytro to re-pin the whole stack to a version your driver supports, so that
        ALL TWELVE jobs use the same build.
   Stopping here rather than silently installing something else."
fi

if [ -n "${SMI_CUDA:-}" ]; then
  SMI_MAJOR="${SMI_CUDA%%.*}"
  if [ "$SMI_MAJOR" -lt "$REQ_CUDA_MAJOR" ]; then
    die "nvidia-smi reports CUDA $SMI_CUDA but the pinned stack needs CUDA ${REQ_CUDA_MAJOR}.x.
   See the note above -- do not substitute a different vLLM build. Stopping."
  fi
fi

# Qwen2.5-7B in bfloat16 is ~14 GiB of weights; at gpu_memory_utilization=0.85 and
# max_model_len=32768 there must be room left for the KV cache.
if [ "$VRAM_MIB" -lt 24000 ]; then
  die "each GPU has ${VRAM_MIB} MiB, which is not enough for Qwen2.5-7B at
   gpu_memory_utilization=0.85 with max_model_len=32768 (~14 GiB weights + KV cache).
   Lowering gpu_memory_utilization is NOT the fix -- it is a locked source-parity value.
   Ask Wytro before changing anything."
fi
echo "   -> driver and VRAM are compatible with the pinned stack."

if [ "$NARCH" -gt 1 ]; then
  cat <<'MIXED'

   NOTE: this node has MORE THAN ONE GPU ARCHITECTURE.
   B200 (sm_10.0) and B300 (sm_10.3) together are fine -- both are Blackwell.
   Leave compute.shard_assignment as "dynamic" so the faster cards are not held back.
   Every shard records which GPU produced it. preflight.py has the details.
MIXED
fi

case "$ARCHS" in *9.0*|*8.*|*7.*)
  cat <<'HOPPER'

   NOTE: a pre-Blackwell GPU (H100/H200/A100/L40S class) is present on this node.
   This workload is restricted to Blackwell (B200 sm_10.0 / B300 sm_10.3) by
   configs/data.yaml, and preflight.py will REFUSE to start if a non-Blackwell card is
   selected. Set compute.gpu_ids in configs/cluster.yaml to just the Blackwell cards.
   Do not widen the allow-list -- it is Wytro's experimental design, not a setting.
HOPPER
  ;;
esac

case "$ARCHS" in *10.*|*11.*|*12.*)
  cat <<'BLACKWELL'

   NOTE: Blackwell detected (B200 sm_10.0 / B300 sm_10.3) -- this is the target.
   The original data was generated on H100 (sm_90) with FlashAttention v3, which is
   Hopper-only; vLLM will choose a different attention backend on these cards. Expected,
   and recorded per shard. Step 5 below runs a real generation, which is what proves the
   pinned build actually has working kernels for this architecture -- do not skip it.
BLACKWELL
  ;;
esac

# ===========================================================================
say "2/5  Creating the environment: $ENV_NAME (python $PY_VERSION)"
# ===========================================================================
if command -v conda >/dev/null 2>&1; then
  CONDA_BASE="$(conda info --base)"
  # shellcheck disable=SC1091
  source "$CONDA_BASE/etc/profile.d/conda.sh"
  if conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
    echo "   env '$ENV_NAME' already exists -> reusing"
  else
    conda create -y -n "$ENV_NAME" "python=$PY_VERSION"
  fi
  conda activate "$ENV_NAME"
  ACTIVATE_LINE="source $CONDA_BASE/etc/profile.d/conda.sh && conda activate $ENV_NAME"
else
  echo "   conda not found -> falling back to a venv at $REPO_ROOT/.venv"
  python3 -c 'import sys; sys.exit(0 if sys.version_info[:2]==(3,12) else 1)' || die \
"conda is not installed and the system python is $(python3 -V 2>&1), not $PY_VERSION.
   Install miniconda (recommended) or provide a python $PY_VERSION, then re-run."
  python3 -m venv "$REPO_ROOT/.venv"
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.venv/bin/activate"
  ACTIVATE_LINE="source $REPO_ROOT/.venv/bin/activate"
fi
python -V

# ===========================================================================
say "3/5  Installing the pinned stack"
# ===========================================================================
python -m pip install --upgrade pip

# torch first, from the cu130 index, so the vLLM install cannot pull a different build.
python -m pip install --index-url "$TORCH_INDEX" \
  "torch==${PIN_TORCH}" "torchvision==0.26.0" "torchaudio==${PIN_TORCH}"

python -m pip install \
  "vllm==${PIN_VLLM}" \
  "transformers==${PIN_TRANSFORMERS}" \
  "tokenizers==${PIN_TOKENIZERS}" \
  "huggingface_hub==${PIN_HFHUB}" \
  "numpy==${PIN_NUMPY}" \
  "pyarrow==${PIN_PYARROW}" \
  "safetensors==${PIN_SAFETENSORS}" \
  "triton==${PIN_TRITON}" \
  "flashinfer-python==${PIN_FLASHINFER}" \
  "xgrammar==${PIN_XGRAMMAR}" \
  "msgspec==${PIN_MSGSPEC}" \
  "datasets==${PIN_DATASETS}" \
  "hf_transfer==${PIN_HFTRANSFER}" \
  "zstandard==${PIN_ZSTANDARD}" \
  "PyYAML==${PIN_PYYAML}"

# ===========================================================================
say "4/5  Import check"
# ===========================================================================
python - <<'PYCHK'
import sys
mods = ["torch", "vllm", "transformers", "tokenizers", "huggingface_hub", "numpy",
        "pyarrow", "datasets", "hf_transfer", "zstandard", "yaml"]
bad = []
for m in mods:
    try:
        mod = __import__(m)
        print(f"   OK   {m:18s} {getattr(mod, '__version__', '?')}")
    except Exception as e:
        bad.append(m); print(f"   FAIL {m:18s} {e}")
import torch
print(f"   torch.version.cuda = {torch.version.cuda}   cuda_available = {torch.cuda.is_available()}")
if not torch.cuda.is_available():
    print("   *** torch cannot see a GPU. Fix this before running anything.", file=sys.stderr)
    sys.exit(2)
expect = {"torch": "2.11.0", "vllm": "0.22.0", "transformers": "5.9.0"}
import importlib.metadata as md
for k, v in expect.items():
    got = md.version(k)
    if got.split("+")[0] != v:
        print(f"   *** {k} is {got}, expected {v} -- generation behaviour may differ "
              f"from the source run. STOP and ask Wytro.", file=sys.stderr)
        sys.exit(2)
if bad:
    sys.exit(2)
print("   all imports OK, versions match the pins")

# Does this torch build actually carry kernels for every card in this box?
built = set(torch.cuda.get_arch_list())
print(f"   torch built for: {sorted(built)}")
bad = []
for i in range(torch.cuda.device_count()):
    p = torch.cuda.get_device_properties(i)
    cc = f"sm_{p.major}{p.minor}"
    if cc in built:
        print(f"   OK   GPU {i} {p.name:28s} {cc}  native kernels")
    elif any(a.startswith(f"sm_{p.major}") for a in built):
        print(f"   WARN GPU {i} {p.name:28s} {cc}  no exact kernels; will PTX-JIT")
    else:
        print(f"   FAIL GPU {i} {p.name:28s} {cc}  NO kernels in this build")
        bad.append((i, p.name, cc))
if bad:
    print("   *** This pinned torch build cannot run:", bad, file=sys.stderr)
    print("   *** Do NOT install a different torch/vLLM to work around it -- a different"
          "\n       build changes generation behaviour and destroys comparability across"
          "\n       the arms. Stop and ask Wytro.", file=sys.stderr)
    sys.exit(2)
PYCHK

# ===========================================================================
say "5/5  One-prompt generation check"
# ===========================================================================
if [ "$SKIP_GEN" = "1" ]; then
  echo "   skipped (--skip-gen-check)"
else
  MODEL_HINT=""
  if [ -f "$REPO_ROOT/configs/cluster.yaml" ]; then
    MODEL_HINT=$(python - "$REPO_ROOT" <<'PYH'
import sys, pathlib, re
t = (pathlib.Path(sys.argv[1]) / "configs" / "cluster.yaml").read_text()
m = re.search(r'^\s*model_dir:\s*"?([^"\n]+)"?', t, re.M)
v = (m.group(1).strip() if m else "")
print("" if ("<" * 3) in v else v)
PYH
)
  fi
  REAL_MODEL=""
  if [ -n "$MODEL_HINT" ] && [ -f "$MODEL_HINT/qwen2.5-7b-instruct/config.json" ]; then
    REAL_MODEL="$MODEL_HINT/qwen2.5-7b-instruct"
  fi
  MODEL_ARG="${REAL_MODEL:-Qwen/Qwen2.5-0.5B-Instruct}"
  echo "   generating with: $MODEL_ARG"
  echo "   (on a mixed fleet this proves ONE card works; preflight.py step 10 and the"
  echo "    first real job exercise the rest)"
  [ -z "$REAL_MODEL" ] && echo "   (the real model is not downloaded yet, so a tiny stand-in is used;" \
                               "this only proves the vLLM install works)"
  python - "$MODEL_ARG" <<'PYGEN'
import sys
from vllm import LLM, SamplingParams
model = sys.argv[1]
llm = LLM(model=model, tensor_parallel_size=1, dtype="bfloat16",
          gpu_memory_utilization=0.60, max_model_len=2048)
out = llm.generate(["Say 'the vLLM install works' and nothing else."],
                   SamplingParams(temperature=0, top_p=1.0, max_tokens=24))
print("   model said:", repr(out[0].outputs[0].text.strip()[:120]))
print("   generation check PASSED")
PYGEN
fi

cat <<EOF

===============================================================================
Environment ready: $ENV_NAME

Paste this EXACT line into configs/cluster.yaml under env.activate_cmd:

  activate_cmd: "$ACTIVATE_LINE"

Next:  python scripts/check_placeholders.py
===============================================================================
EOF
